If the tracking id is passed when calling the method it is giving exception.
AttributeError: 'Gateway' object has no attribute 'tracking_id'.

So if the id is passed the else condition will set the tracking id equal to the one that is passed when method is called.